export const STATES = [
  {id:'odisha', ic:'🏛️', name:'Odisha', sig:'Sambalpuri Ikat', pat:'diamond', c1:'#4E1420', c2:'#F1E6CE',
    sarees:['Sambalpuri','Bomkai','Pasapalli','Kotpad','Berhampuri Silk','Nuapatna Khandua','Gopalpur Tussar','Habaspuri','Sonpuri','Dolabedi','Sonepuri Silk','Maniabandha Ikat']},
  {id:'bengal', ic:'👑', name:'West Bengal', sig:'Baluchari', pat:'motif', c1:'#3A0F1C', c2:'#F0D27E',
    sarees:['Baluchari','Swarnachari','Jamdani','Dhakai Jamdani','Tant','Garad','Murshidabad Silk','Begumpuri','Kantha Stitch Saree','Bengal Cotton','Bishnupuri Silk']},
  {id:'up', ic:'👑', name:'Uttar Pradesh', sig:'Banarasi Silk', pat:'jaal', c1:'#5A1420', c2:'#C9A227',
    sarees:['Banarasi Silk','Banarasi Katan','Banarasi Organza','Banarasi Tissue','Banarasi Georgette','Banarasi Jangla','Banarasi Tanchoi','Banarasi Cutwork','Banarasi Butidar','Banarasi Brocade']},
  {id:'tn', ic:'👑', name:'Tamil Nadu', sig:'Kanjivaram Silk', pat:'temple', c1:'#153A2C', c2:'#F0D27E',
    sarees:['Kanchipuram Silk','Kanjivaram Silk','Arani Silk','Chettinad Cotton','Coimbatore Cotton','Salem Silk','Madurai Cotton','Sungudi Cotton','Thirubuvanam Silk','Kovai Cotton']},
  {id:'ka', ic:'👑', name:'Karnataka', sig:'Mysore Silk', pat:'check', c1:'#33132C', c2:'#C9A227',
    sarees:['Mysore Silk','Ilkal Saree','Molakalmuru Saree','Udupi Cotton','Kasuti Saree']},
  {id:'ap', ic:'👑', name:'Andhra Pradesh', sig:'Pochampally Ikat', pat:'diamond', c1:'#7C1F2C', c2:'#F1E6CE',
    sarees:['Mangalagiri Cotton','Venkatagiri Saree','Uppada Silk','Dharmavaram Silk','Gadwal Saree','Narayanpet Saree','Chirala Cotton','Pochampally Silk','Pochampally Ikat','Guntur Cotton']},
  {id:'tg', ic:'👑', name:'Telangana', sig:'Pochampally Ikat', pat:'diamond', c1:'#8B5E2E', c2:'#F1E6CE',
    sarees:['Pochampally Ikat','Gadwal Silk','Narayanpet Cotton','Siddipet Gollabhama','Kothakota Saree']},
  {id:'gj', ic:'👑', name:'Gujarat', sig:'Patola', pat:'dots', c1:'#7C1F2C', c2:'#F1E6CE',
    sarees:['Patola','Rajkot Patola','Bandhani','Gharchola','Panetar','Kutchi Bandhani','Mashru Silk','Ajrakh Saree','Tangaliya Saree']},
  {id:'rj', ic:'👑', name:'Rajasthan', sig:'Leheriya', pat:'wave', c1:'#8B5E2E', c2:'#F1E6CE',
    sarees:['Leheriya','Bandhej','Kota Doria','Kota Cotton','Sanganeri Print','Bagru Print','Zari Kota','Chundri']},
  {id:'mp', ic:'👑', name:'Madhya Pradesh', sig:'Chanderi', pat:'stripe', c1:'#8B5E2E', c2:'#F0D27E',
    sarees:['Chanderi','Maheshwari','Bagh Print Saree','Batik Saree']},
  {id:'mh', ic:'👑', name:'Maharashtra', sig:'Paithani', pat:'peacock', c1:'#33132C', c2:'#F0D27E',
    sarees:['Paithani','Yeola Paithani','Nauvari','Narayan Peth','Karvati Kathi','Kosa Silk']},
  {id:'cg', ic:'👑', name:'Chhattisgarh', sig:'Kosa Silk', pat:'texture', c1:'#4E1420', c2:'#C9A227',
    sarees:['Kosa Silk','Bastar Cotton']},
  {id:'br', ic:'👑', name:'Bihar', sig:'Bhagalpuri Silk', pat:'motif', c1:'#4E1420', c2:'#C9A227',
    sarees:['Bhagalpuri Silk','Tussar Silk','Madhubani Painted Saree','Sujani Saree']},
  {id:'jh', ic:'👑', name:'Jharkhand', sig:'Tussar Silk', pat:'texture', c1:'#8B5E2E', c2:'#F1E6CE',
    sarees:['Tussar Silk','Tribal Handloom Saree']},
  {id:'as', ic:'👑', name:'Assam', sig:'Muga Silk', pat:'texture', c1:'#8B5E2E', c2:'#F0D27E',
    sarees:['Muga Silk','Eri Silk','Pat Silk','Mekhela Chador','Assam Silk']},
  {id:'ml', ic:'👑', name:'Meghalaya', sig:'Ryndia Silk', pat:'texture', c1:'#153A2C', c2:'#8B5E2E',
    sarees:['Ryndia Silk Saree']},
  {id:'mn', ic:'👑', name:'Manipur', sig:'Moirang Phee', pat:'stripe', c1:'#4E1420', c2:'#F1E6CE',
    sarees:['Moirang Phee','Leirum Saree']},
  {id:'kl', ic:'👑', name:'Kerala', sig:'Kasavu Saree', pat:'border', c1:'#F1E6CE', c2:'#C9A227',
    sarees:['Kasavu Saree','Settu Mundu','Kerala Cotton','Balaramapuram Saree']},
  {id:'pb', ic:'👑', name:'Punjab', sig:'Phulkari', pat:'floral', c1:'#7C1F2C', c2:'#F0D27E',
    sarees:['Phulkari Saree','Punjabi Cotton Saree']},
  {id:'hp', ic:'👑', name:'Himachal Pradesh', sig:'Kullu Handloom', pat:'stripe', c1:'#33132C', c2:'#C9A227',
    sarees:['Kullu Handloom Saree']},
  {id:'jk', ic:'👑', name:'Jammu & Kashmir', sig:'Kashmiri Pashmina', pat:'paisley', c1:'#153A2C', c2:'#F0D27E',
    sarees:['Kashmiri Silk Saree','Sozni Embroidery Saree','Pashmina Saree']},
  {id:'goa', ic:'👑', name:'Goa', sig:'Kunbi Saree', pat:'check', c1:'#8B5E2E', c2:'#F1E6CE',
    sarees:['Kunbi Saree']},
];

export const WEAVES = [
  {n:'01', name:'Sambalpuri Bandha', desc:'Ikat-tied diamonds in maroon and ivory, the pattern born in the thread itself.', c1:'#5A1420', c2:'#F1E6CE', pat:'diamond'},
  {n:'02', name:'Kanjivaram Silk', desc:'Temple borders in gold zari against deep emerald silk.', c1:'#153A2C', c2:'#C9A227', pat:'temple'},
  {n:'03', name:'Banarasi Brocade', desc:'Mughal jaal florals woven through wine and antique gold.', c1:'#3A0F1C', c2:'#8B5E2E', pat:'jaal'},
  {n:'04', name:'Paithani', desc:'Peacock-feather palloos on royal plum, bordered in gold.', c1:'#33132C', c2:'#F0D27E', pat:'peacock'},
  {n:'05', name:'Patola Double Ikat', desc:'Geometric precision, tied and dyed on both warp and weft.', c1:'#7C1F2C', c2:'#F1E6CE', pat:'diamond'},
  {n:'06', name:'Jamdani Muslin', desc:'Featherweight florals, hand-picked into sheer ivory cotton.', c1:'#E7D8B7', c2:'#8B5E2E', pat:'floral'},
  {n:'07', name:'Chanderi Sheer', desc:'Champagne stripes catching light like rose gold thread.', c1:'#8B5E2E', c2:'#F0D27E', pat:'stripe'},
  {n:'08', name:'Tussar Wild Silk', desc:'Textured, undyed warmth — the most honest of all our silks.', c1:'#4E1420', c2:'#C9A227', pat:'texture'},
];

export const FABRICS = ['Pure Silk','Mulberry Silk','Muga Silk','Eri Silk','Tussar Silk','Cotton','Linen','Organza','Tissue','Chiffon','Georgette','Crepe','Satin','Velvet','Net','Muslin','Kota Cotton','Khadi Cotton','Bamboo Silk','Modal Silk','Cotton Silk','Silk Cotton','Raw Silk','Art Silk','Poly Silk'];
export const WEAVE_STYLES = ['Ikat','Double Ikat','Single Ikat','Jacquard','Brocade','Zari Weaving','Handloom','Powerloom','Jamdani','Kalamkari','Kantha','Kasuti','Phulkari','Chikankari','Block Print','Bagru Print','Sanganeri Print','Batik','Ajrakh','Bandhani','Leheriya','Tie & Dye','Hand Painted','Digital Print','Embroidery','Mirror Work','Sequence Work','Resham Work','Stone Work','Gota Patti'];
export const OCCASIONS = ['Bridal Sarees','Wedding Sarees','Reception Sarees','Festive Sarees','Temple Sarees','Party Wear Sarees','Designer Sarees','Luxury Couture Sarees','Office Wear Sarees','Daily Wear Sarees','Casual Sarees','Celebrity Collection','Handloom Collection','Heritage Collection','Royal Collection','Premium Collection','Limited Edition Sarees'];
