/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FloralBandRouteImport } from './routes/floral-band'
import { Route as FloralBand2RouteImport } from './routes/floral-band-2'
import { Route as GeometricBandRouteImport } from './routes/geometric-band'
import { Route as LotusBandRouteImport } from './routes/lotus-band'
import { Route as PaisleyBandRouteImport } from './routes/paisley-band'
import { Route as RosetteBandRouteImport } from './routes/rosette-band'
import { Route as TulipBandRouteImport } from './routes/tulip-band'
import { Route as VineBandRouteImport } from './routes/vine-band'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FloralBandRoute = FloralBandRouteImport.update({
  id: '/floral-band',
  path: '/floral-band',
  getParentRoute: () => rootRouteImport,
} as any)
const FloralBand2Route = FloralBand2RouteImport.update({
  id: '/floral-band-2',
  path: '/floral-band-2',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometricBandRoute = GeometricBandRouteImport.update({
  id: '/geometric-band',
  path: '/geometric-band',
  getParentRoute: () => rootRouteImport,
} as any)
const LotusBandRoute = LotusBandRouteImport.update({
  id: '/lotus-band',
  path: '/lotus-band',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisleyBandRoute = PaisleyBandRouteImport.update({
  id: '/paisley-band',
  path: '/paisley-band',
  getParentRoute: () => rootRouteImport,
} as any)
const RosetteBandRoute = RosetteBandRouteImport.update({
  id: '/rosette-band',
  path: '/rosette-band',
  getParentRoute: () => rootRouteImport,
} as any)
const TulipBandRoute = TulipBandRouteImport.update({
  id: '/tulip-band',
  path: '/tulip-band',
  getParentRoute: () => rootRouteImport,
} as any)
const VineBandRoute = VineBandRouteImport.update({
  id: '/vine-band',
  path: '/vine-band',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/floral-band': typeof FloralBandRoute
  '/floral-band-2': typeof FloralBand2Route
  '/geometric-band': typeof GeometricBandRoute
  '/lotus-band': typeof LotusBandRoute
  '/paisley-band': typeof PaisleyBandRoute
  '/rosette-band': typeof RosetteBandRoute
  '/tulip-band': typeof TulipBandRoute
  '/vine-band': typeof VineBandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/floral-band': typeof FloralBandRoute
  '/floral-band-2': typeof FloralBand2Route
  '/geometric-band': typeof GeometricBandRoute
  '/lotus-band': typeof LotusBandRoute
  '/paisley-band': typeof PaisleyBandRoute
  '/rosette-band': typeof RosetteBandRoute
  '/tulip-band': typeof TulipBandRoute
  '/vine-band': typeof VineBandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/floral-band': typeof FloralBandRoute
  '/floral-band-2': typeof FloralBand2Route
  '/geometric-band': typeof GeometricBandRoute
  '/lotus-band': typeof LotusBandRoute
  '/paisley-band': typeof PaisleyBandRoute
  '/rosette-band': typeof RosetteBandRoute
  '/tulip-band': typeof TulipBandRoute
  '/vine-band': typeof VineBandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/floral-band'
    | '/floral-band-2'
    | '/geometric-band'
    | '/lotus-band'
    | '/paisley-band'
    | '/rosette-band'
    | '/tulip-band'
    | '/vine-band'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/floral-band'
    | '/floral-band-2'
    | '/geometric-band'
    | '/lotus-band'
    | '/paisley-band'
    | '/rosette-band'
    | '/tulip-band'
    | '/vine-band'
  id:
    | '__root__'
    | '/'
    | '/floral-band'
    | '/floral-band-2'
    | '/geometric-band'
    | '/lotus-band'
    | '/paisley-band'
    | '/rosette-band'
    | '/tulip-band'
    | '/vine-band'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FloralBandRoute: typeof FloralBandRoute
  FloralBand2Route: typeof FloralBand2Route
  GeometricBandRoute: typeof GeometricBandRoute
  LotusBandRoute: typeof LotusBandRoute
  PaisleyBandRoute: typeof PaisleyBandRoute
  RosetteBandRoute: typeof RosetteBandRoute
  TulipBandRoute: typeof TulipBandRoute
  VineBandRoute: typeof VineBandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floral-band': {
      id: '/floral-band'
      path: '/floral-band'
      fullPath: '/floral-band'
      preLoaderRoute: typeof FloralBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floral-band-2': {
      id: '/floral-band-2'
      path: '/floral-band-2'
      fullPath: '/floral-band-2'
      preLoaderRoute: typeof FloralBand2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometric-band': {
      id: '/geometric-band'
      path: '/geometric-band'
      fullPath: '/geometric-band'
      preLoaderRoute: typeof GeometricBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotus-band': {
      id: '/lotus-band'
      path: '/lotus-band'
      fullPath: '/lotus-band'
      preLoaderRoute: typeof LotusBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paisley-band': {
      id: '/paisley-band'
      path: '/paisley-band'
      fullPath: '/paisley-band'
      preLoaderRoute: typeof PaisleyBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosette-band': {
      id: '/rosette-band'
      path: '/rosette-band'
      fullPath: '/rosette-band'
      preLoaderRoute: typeof RosetteBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tulip-band': {
      id: '/tulip-band'
      path: '/tulip-band'
      fullPath: '/tulip-band'
      preLoaderRoute: typeof TulipBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vine-band': {
      id: '/vine-band'
      path: '/vine-band'
      fullPath: '/vine-band'
      preLoaderRoute: typeof VineBandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FloralBandRoute: FloralBandRoute,
  FloralBand2Route: FloralBand2Route,
  GeometricBandRoute: GeometricBandRoute,
  LotusBandRoute: LotusBandRoute,
  PaisleyBandRoute: PaisleyBandRoute,
  RosetteBandRoute: RosetteBandRoute,
  TulipBandRoute: TulipBandRoute,
  VineBandRoute: VineBandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
